version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
  mysql:
    depends_on: 
    - php-apache
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "website_name"
    volumes:
      - dbData:/var/lib/mysql
    restart: always
volumes:
  app:
  dbData: